clc
%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\Github\Two-link-Robotic-Arm\G1.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/06 19:54:29

%% Initialize variables.
filename = 'D:\Github\Two-link-Robotic-Arm\Shoaib.txt';
delimiter = ' ';

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Allocate imported array to column variable names
x = cell2mat(raw(:, 2))/1000;
y = cell2mat(raw(:, 3))/1000;

% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp;
%% Create your Robotic Arm
L(1) = Link([0      0      0.20       0      0      0]);
L(2) = Link([0      0      0.15       0      0      0]);
% % Build a serial robot object
R2 = SerialLink(L(1:2), 'name', 'TwoLink');
% 
% % Robot base coordinates (cartesian space)
% R2.base=transl(0,0,0);

% Desired points in cartesian space (meters) 
% p0 = [0.05 0.4 0];
% p1 = transl(-0.2,0.2,0);
% p2 = transl(0.3,0.02,0)
% p3 = transl(-.15,-0.2,0)
% p4 = transl(-0.2,0.2,0);
% p5 = transl(0.3,0.380,0);
x_len = length(x);
hold on
view(-0.6,0.8);
xlim([-0.6,1]);
ylim([-0.6,1]); 
zlim([-0.1,0.2]); 

% From point 1 to 2
pp1 = transl(x(1,1),y(1,1),0);
pp2 = transl(x(2,1),y(2,1),0);
crt_sp1 = ctraj(pp1,pp2,x_len);
crt_ik1  = R2.ikine(crt_sp1,'mask',[1 1 0 0 0 0]);

% From point 2 to 3
pp3 = transl(x(3,1),y(3,1),0);
crt_sp2 = ctraj(pp2,pp3,50);
crt_ik2  = R2.ikine(crt_sp2,'mask',[1 1 0 0 0 0]);
% 
% pp4 = transl(-0.2,-0.2,0);
% crt_sp3 = ctraj(pp3,pp4,50);
% crt_ik3  = R2.ikine(crt_sp3,'mask',[1 1 0 0 0 0]);
% 
% pp5 = transl(-0.2,0.2,0);
% crt_sp4 = ctraj(pp4,pp5,50);
% crt_ik4  = R2.ikine(crt_sp4,'mask',[1 1 0 0 0 0]);

for i=1:1:x_len
    fd1=R2.fkine(crt_ik1(i,:));
     j = transpose(fd1.t);
    plot2(j,'r.')    ;
     R2.plot(crt_ik1(i,:)) ;
end


for i=1:1:x_len
    fd2=R2.fkine(crt_ik1(i,:));
     j = transpose(fd2.t);
    plot2(j,'r.')    ;
     R2.plot(crt_ik2(i,:)) ;
end


